### ISSUE TITLE
Error Permission Denied - during ak build

### ISSUE THREAD

**Issue by mbcosta** [akretion/voodoo#18]
Hi
   The error happen when you run command ak build
Log Message

While:
  Installing openerp.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/magno/.voodoo/shared/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 1987, in main
    getattr(buildout, command)(args)
  File "/home/magno/.voodoo/shared/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 668, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/magno/.voodoo/shared/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 1409, in _call
    return f()
  File "/home/magno/.voodoo/shared/eggs/anybox.recipe.odoo-1.9.1-py2.7.egg/anybox/recipe/odoo/base.py", line 856, in install
    self.merge_requirements()
  File "/home/magno/.voodoo/shared/eggs/anybox.recipe.odoo-1.9.1-py2.7.egg/anybox/recipe/odoo/server.py", line 87, in merge_requirements
    openerp_project_name = self.develop(openerp_dir)
  File "/home/magno/.voodoo/shared/eggs/anybox.recipe.odoo-1.9.1-py2.7.egg/anybox/recipe/odoo/base.py", line 473, in develop
    egg_link = zc.buildout.easy_install.develop(src_directory, develop_dir)
  File "/home/magno/.voodoo/shared/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/easy_install.py", line 924, in develop
    tmp3 = tempfile.mkdtemp('build', dir=dest)
  File "/usr/lib/python2.7/tempfile.py", line 333, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 13] Permission denied: '/workspace/develop-eggs/tmphUWM5ybuild'

  To fix the error you just need to set permission on the folder
$ sudo chmod -R 0777 /workspace/develop-eggs

**Comment by bealdav** [comment]
Thanks @mbcosta.

**Comment by renatonlima** [comment]
@bealdav 

When I run ak build, I have one permission error in this folder /home/USER/.voodoo/shared/develop-eggs

**Comment by renatonlima** [comment]
One more message erro during ak build to help:

Traceback (most recent call last):
  File "/home/renato/.voodoo/shared/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 1987, in main
    getattr(buildout, command)(args)
  File "/home/renato/.voodoo/shared/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 517, in install
    self._maybe_upgrade()
  File "/home/renato/.voodoo/shared/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 952, in _maybe_upgrade
    allow_hosts = self._allow_hosts
  File "/home/renato/.voodoo/shared/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/easy_install.py", line 847, in install
    allow_hosts=allow_hosts)
  File "/home/renato/.voodoo/shared/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/easy_install.py", line 222, in __init__
    self._env = pkg_resources.Environment(path)
  File "/home/renato/.voodoo/shared/eggs/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 1009, in __init__
    self.scan(search_path)
  File "/home/renato/.voodoo/shared/eggs/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 1038, in scan
    for dist in find_distributions(item):
  File "/home/renato/.voodoo/shared/eggs/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 2129, in find_on_path
    with open(os.path.join(path_item, entry)) as entry_file:
IOError: [Errno 13] Permission denied: '/home/renato/.voodoo/shared/develop-eggs/odoo.egg-link'

**Comment by rvalyi** [comment]
implemented work around in https://github.com/akretion/voodoo-image/commit/a6bf06c08e24323c66b21b1e49875d9d319890ac
