### ISSUE TITLE
voodoo new doesn t generate docker-compose.yml file

### ISSUE THREAD

**Issue by rvalyi** [akretion/voodoo#46]
rvalyi@rvalyi-laptop:~$ voodoo new test
...
rvalyi@rvalyi-laptop:~$ cd test
rvalyi@rvalyi-laptop:~/test$ voodoo run
Traceback (most recent call last):
  File "/usr/local/bin/voodoo", line 9, in <module>
    load_entry_point('voodoo-cli==2.0.2', 'console_scripts', 'voodoo')()
  File "/usr/local/lib/python2.7/dist-packages/voodoo/main.py", line 402, in main
    Voodoo.run()
  File "/usr/local/lib/python2.7/dist-packages/plumbum/cli/application.py", line 485, in run
    inst, retcode = subapp.run(argv, exit = False)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/cli/application.py", line 457, in run
    inst = cls(argv.pop(0))
  File "/usr/local/lib/python2.7/dist-packages/voodoo/main.py", line 194, in __init__
    self.main_service = self._get_main_service()
  File "/usr/local/lib/python2.7/dist-packages/voodoo/main.py", line 183, in _get_main_service
    dc_file = open('docker-compose.yml', 'r')
IOError: [Errno 2] No such file or directory: 'docker-compose.yml'

**Comment by jpoa** [comment]
I have the same issue.

Any version know to have this solved? Would be happy to go around this if needed.

**Comment by sebastienbeau** [comment]
Oups sorry, I miss to add the docker-compose file in the template. It's fix in the version 7.0 8.0 and 9.0 https://github.com/akretion/voodoo-template/commit/6dd2c6bda43a04fac858e12c19cf4b32aa47f5e2
