### ISSUE TITLE
ak run: OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by rvalyi** [akretion/voodoo#47]
```
voodoo new test
cd test
odoo@3d84a363e332:/workspace$ ak run
Traceback (most recent call last):
  File "/usr/local/bin/ak", line 9, in <module>
    load_entry_point('ak==1.0.0', 'console_scripts', 'ak')()
  File "/usr/local/lib/python2.7/dist-packages/ak/main.py", line 316, in main
    Ak.run()
  File "/usr/local/lib/python2.7/dist-packages/plumbum/cli/application.py", line 485, in run
    inst, retcode = subapp.run(argv, exit = False)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/cli/application.py", line 480, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/lib/python2.7/dist-packages/ak/main.py", line 98, in main
    return self._exec(cmd, params)
  File "/usr/local/lib/python2.7/dist-packages/ak/main.py", line 69, in _exec
    return self.parent._exec(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ak/main.py", line 44, in _exec
    os.execvpe(cmd, [cmd] + args, local.env)
  File "/usr/lib/python2.7/os.py", line 355, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 370, in _execvpe
    func(file, *argrest)
OSError: [Errno 2] No such file or directory
```

cc @sebastienbeau

**Comment by rvalyi** [comment]
ok I had to do ak build. Still ak run should trigger ak build idf needed instead of just crashing
